awvideobanner_form_configuration:
  path: /awvideobanner/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwVideoBanner\Controller\AdminConfigurationController::index'
    _legacy_controller: AdminAwVideoBanner
    _legacy_link: AdminAwVideoBanner
